inc:
  # Blog Information
  title:        "aria42"
  subtitle:     "Musings on everything and then some"
  cover_image:  blog-cover.jpg
  logo:         logo.svg

  # Company information
  company:      aria42.com
  url:          http://aria42.com/
  facebook:     aria42
  twitter:      aria42
  about_link:   http://aria42.com/about/

  # Product Information
  # product_link: http://aria42.com
  # tagline:      "Musings on everything"


  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true

 # Analytics
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html


  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Open+Sans:400,500,600,700|Roboto:400,500,600,700|Raleway:400,500,600,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

hostname: "localhost:4000"
url:         http://localhost:4000
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0

relative_permalinks: true

permalink:     "/blog/:year/:month/:title"
paginate_path: 'blog/page:num'
paginate: 10

markdown: kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false

gems:
- jekyll-assets